# ==================================
# Web Services Section
# ==================================
services:
  - type: web
    name: inventory-backend-final
    env: spring # Spring Boot ku idhu sariyana setting
    region: Singapore
    plan: free
    rootDir: backend
    buildCommand: ./mvnw clean install
    startCommand: java -jar target/*.jar
    autoDeploy: true # Inime push panna, amaidhiya deploy aagidum
    envVars:
      - fromDatabase:
          name: inventory-db-final
          property: connectionString
        key: SPRING_DATASOURCE_URL
      - fromDatabase:
          name: inventory-db-final
          property: user
        key: SPRING_DATASOURCE_USERNAME
      - fromDatabase:
          name: inventory-db-final
          property: password
        key: SPRING_DATASOURCE_PASSWORD
      - key: FRONTEND_URL
        value: https://inventory-management-system-e4kz.vercel.app

# ==================================
# Database Services Section
# ==================================
databases:
  - name: inventory-db-final
    region: Singapore
    plan: free